### ISSUE TITLE
 The mouse wheel does not scroll the file open/save dialog

### ISSUE THREAD

**Issue by haxmeister** [haje61/App-Codit#1]
The mouse wheel does not scroll the file open/save dialog

**Comment by haje61** [comment]
It doesn't. This is an issue with Tk. Besides for Text widgets Tk is really bad at wheel scrolling stuff. For this I published Tk::DynaMouseWheelBind. So I could fix it...

However, in Tk::AppWindow 0.17 I will implement a completely redesigned file dialog, that also allows to open multiple files at once.

**Comment by haje61** [comment]
Fixed!
App::Codit version 0.13 is on CPAN
Tk::AppWindow version 0.17 is on CPAN
